pipeline {
    agent any
    stages {
        stage('Build Image') {
            steps {
                script {
                    // Assuming your Dockerfile is in the root directory
                   sh 'docker build -t my-image:1 .'
                }
            }
        }
    }
}
