pipeline {
    agent any
    stages {
        stage('Build Image') {
            steps {
                script {
                    // Assuming your Dockerfile is in the root directory
                    docker build -t my-image:latest .
                }
            }
        }
    }
}
